#                                              Day-3 Assignment

# Question-1

In [1]:
import numpy as np

In [2]:
arr=np.arange(2,51,3)
arr
#print(type(arr))

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

# Question-2

In [21]:
l1=[] # creating empty list l1
l2=[] # creating empty list l2
print("l1=",l1,"l2=",l2) # printing Empty lists l1,l2
print("Accepting 5 elements for l1 from user:") # accepting elements for l1 from user
for i in range(5):
    n=int(input())
    l1.append(n)
print("Accepting 5 elements for l2 from user:")    # accepting elements for l2 from user
for i in range(5):
    n=int(input())
    l2.append(n)
print("l1=",l1,"l2=",l2)# printing lists l1,l2 after accepting elements from user
print(type(l1)) # printing type of l1 before converting 
print(type(l2)) # printing type of l2 before converting
l1=np.array(l1) # converting l1 to numpy array
l2=np.array(l2) # converting l2 to numpy array
print(type(l1)) # printing type of l1 after converting
print(type(l2)) # printing type of l2 after converting
arr=np.concatenate((l1,l2)) # concatenation of l1,l2 arrays
print("after concatenation of l1,l2 arrays:",arr) #arr  after concatenation
print("after sorintg elements in arr:",np.sort(arr)) # sorting elements of arr
print("soritng elements in l1 array:",np.sort(l1)) # sorting elements of l1
print("sorting elements in l2 array:",np.sort(l2)) # sorintg elements of l2 

l1= [] l2= []
Accepting 5 elements for l1 from user:
5
4
3
2
1
Accepting 5 elements for l2 from user:
10
9
8
7
6
l1= [5, 4, 3, 2, 1] l2= [10, 9, 8, 7, 6]
<class 'list'>
<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
after concatenation of l1,l2 arrays: [ 5  4  3  2  1 10  9  8  7  6]
after sorintg elements in arr: [ 1  2  3  4  5  6  7  8  9 10]
soritng elements in l1 array: [1 2 3 4 5]
sorting elements in l2 array: [ 6  7  8  9 10]


# Question-3

In [39]:
arr1d=np.arange(1,4) # creating 1 dimension array with elements from 1 to 4-1
print("1d array:\n",arr1d)
print()
arr2d=np.arange(1,13).reshape(3,4) # creating 2 dimension array with elements from 1 to 13-1
print("2d array:\n",arr2d)
print()
arr3d=np.arange(1,25).reshape(2,3,4) # # creating 3 dimension array with elements from 1 to 25-1
print("3d array:\n",arr3d)
# finding Dimensions of ndarray's
print("Dimension of arr1d: ",arr1d.ndim)
print("Dimension of arr2d: ",arr2d.ndim)
print("Dimension of arr3d: ",arr3d.ndim)
print()
# finding size of ndarray's  i.e; no of elements in each array
print("size of arr1d: ",arr1d.size)
print("size of arr2d: ",arr2d.size)
print("size of arr3d: ",arr3d.size)

1d array:
 [1 2 3]

2d array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

3d array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Dimension of arr1d:  1
Dimension of arr2d:  2
Dimension of arr3d:  3

size of arr1d:  3
size of arr2d:  12
size of arr3d:  24


# question-4

# converting 1d array to 2d array by using np.newaxis 

In [47]:
print(np.newaxis is None)

True


In [59]:
a = np.arange(6).reshape(6)
print(a)
print()
print("No. of Dimensions:",a.ndim)

[0 1 2 3 4 5]

No. of Dimensions: 1


In [60]:
print(a[:,np.newaxis])
print("No. of Dimensions:",a[:,None].ndim) # here None is np.newaxis
print("Shape:",a[:,None].shape)
print()
print(a[np.newaxis,:])
print("No. of Dimensions:",a[None,:].ndim)
print("Shape:",a[None,:].shape)


[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
No. of Dimensions: 2
Shape: (6, 1)

[[0 1 2 3 4 5]]
No. of Dimensions: 2
Shape: (1, 6)


In [61]:
print(a[np.newaxis])
print("No. of Dimensions:",a[None].ndim)
print("Shape:",a[None].shape)

[[0 1 2 3 4 5]]
No. of Dimensions: 2
Shape: (1, 6)


# Add a new dimension with np.expand_dims()

In [72]:
a = np.arange(6).reshape(6)
print(a)
print()
print("No. of Dimensions:",a.ndim)

[0 1 2 3 4 5]

No. of Dimensions: 1


In [71]:
print(np.expand_dims(a, 0))
print("No. of Dimensions:",np.expand_dims(a,0).ndim) # adding dimension at 0th position
print(np.expand_dims(a,0).shape)
print()
print(np.expand_dims(a, 1))
print("No. of Dimensions:",np.expand_dims(a,1).ndim) # adding dimension at 1st position
print(np.expand_dims(a,1).shape)
print()

[[0 1 2 3 4 5]]
No. of Dimensions: 2
(1, 6)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
No. of Dimensions: 2
(6, 1)



# Question-5

In [86]:
a=np.array([[1],[8],[9],[6]])
b=np.array([[2],[7],[4],[0]])
c=np.array([[1],[2],[3],[4]])
print("Stack arrays in sequence horizontally (column wise).\n",np.hstack((a,b,c)))
print()
print("Stack arrays in sequence vertically (row wise).\n",np.vstack((a,b,c)))

Stack arrays in sequence horizontally (column wise).
 [[1 2 1]
 [8 7 2]
 [9 4 3]
 [6 0 4]]

Stack arrays in sequence vertically (row wise).
 [[1]
 [8]
 [9]
 [6]
 [2]
 [7]
 [4]
 [0]
 [1]
 [2]
 [3]
 [4]]


#  Question-6

In [106]:
arr=np.array([1,2,3,1,1,6,2,3,8,9,4,8,9])
print("User given array:\n",arr)
print()
unique_items,counts=np.unique(arr,return_counts=True)
#print(unique_items)
#print(counts)
print("unique items followed by their count:")
print(np.asarray((unique_items,counts)))

User given array:
 [1 2 3 1 1 6 2 3 8 9 4 8 9]

unique items followed by their count:
[[1 2 3 4 6 8 9]
 [3 2 2 1 1 2 2]]
